export default  {
  GET_USER: 'GET_USER',
  ADD_USER: 'ADD_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',

  SET_INPUT_NAME: 'SET_INPUT_FIRSTNAME',
  SET_INPUT_EMAIL: 'SET_INPUT_EMAIL',
  SET_INPUT_BODY: 'SET_INPUT_BODY',
  SET_INPUT_ID: 'SET_INPUT_ID',
  RESET_INPUT: 'RESET_INPUT',
}
